name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v2
      with:
        node-version: "22.x"
        registry-url: "https://registry.npmjs.org"

    - run: npm publish --access public
      working-directory: Packages/ai.videokit.videokit